[tool.poetry]
name = "radiobee-aligner"
version = "0.1.0"
description = ""
authors = ["ffreemt"]

[tool.poetry.dependencies]
python = "^3.7"
gradio = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
